import test from 'node:test';import assert from 'node:assert/strict';
import '../web/js/enemy-art.js';import '../web/js/campaign.js';import '../web/js/player-rules.js';import '../web/js/projectile-rules.js';import '../web/js/weapon-art.js';import '../web/js/original-rules.js';
const {Game,STEP,deathScale,deathTransform}=StarfallCore,C=DemonStarCampaign;
const falling=[3,4,5,6,9,12,13,15,18];
function boss(stage){const g=new Game(51);g.start(1,stage,true);g.phase='playing';g.launch=null;g.recordEvents=[];g.spawnRecord(g.stage.map.events.find(r=>C.definitions[C.byId[r[2]]].flags&1));g.boss.x=130;g.boss.y=120;return g;}
test('all eighteen Bosses follow the original ground/fall flag gate',()=>{
  for(let stage=1;stage<=18;stage++){const g=boss(stage),e=g.boss;g.killEnemy(e);assert.equal(!!e.dying,falling.includes(stage),'stage '+stage);assert.equal(!!e.dead,!falling.includes(stage));assert.equal(g.phase,falling.includes(stage)?'playing':'aftermath');assert.ok(g.effects.length>=6);assert.equal(g.effects[0].bossPhase,falling.includes(stage)?'start':'finish');assert.equal(g.score,falling.includes(stage)?0:e.def.score);}
});
test('reference state four retains hull size, two blast phases and exact fixed-point threshold order',()=>{
  const g=boss(3),e=g.boss;g.killEnemy(e);assert.equal(e.deathMode,4);assert.equal(g.effects.length,8);for(let i=0;i<49;i++)g.updateEnemyState(e);assert.equal(e.fallFixed,49*0x5555);assert.equal(e.dead,false);assert.equal(g.score,0);const at=deathTransform(e);assert.equal(at.scale,1);assert.equal(at.y,104);assert.equal(at.x,130+16*e.fallDirection);g.updateEnemyState(e);assert.equal(e.dead,true);assert.equal(e.deathTicks,50);const ending=g.effects.filter(v=>v.bossPhase==='finish');assert.equal(ending.length,8);assert.equal(ending.slice(0,4).reduce((a,v)=>a+v.x,0)/4,at.x);assert.equal(ending.slice(0,4).reduce((a,v)=>a+v.y,0)/4,at.y);const score=g.score;g.finishEnemy(e);assert.equal(g.score,score);assert.equal(g.kills,1);
});
test('a paused Boss death does not advance and the alternative projection remains available',()=>{
  const g=boss(4),e=g.boss;g.killEnemy(e);g.update(STEP);g.pause();const before=JSON.stringify(g);g.update(.2);assert.equal(JSON.stringify(g),before);assert.equal(deathScale(0),1);assert.equal(deathScale(40.75),deathScale(40));assert.ok(deathScale(120)<deathScale(40));assert.ok(deathScale(120)>.62&&deathScale(120)<.63);
});
test('original state three still finishes on update 39 and projects its final blast',()=>{const g=boss(3),e=g.boss;g.killEnemy(e,g.player,3);for(let i=0;i<38;i++)g.updateEnemyState(e);assert.equal(e.fall,122);assert.equal(e.dead,false);const at=deathTransform(e);assert.ok(at.scale<1);g.updateEnemyState(e);assert.equal(e.deathTicks,39);assert.equal(e.dead,true);assert.equal(g.effects.filter(v=>v.bossPhase==='finish').slice(0,4).reduce((a,v)=>a+v.x,0)/4,at.x);});
test('edge drift follows original direction gates and visual blast randomness is isolated',()=>{for(const [x,direction] of [[40,-1],[370,1]]){const g=boss(3),e=g.boss;e.x=x;g.killEnemy(e);assert.equal(e.fallDirection,direction);const state=g.random.state();g.bossBurst(e,'finish');assert.equal(g.random.state(),state);assert.equal(g.targetable(e),false);g.updateEnemyState(e);assert.equal(e.burning,false);}});
