// 双人完整 App 流程及第三人拒绝；原生 TCP 另行验证。
// Two-player app flow and third-player rejection; native TCP is checked separately.
import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true}),pages=[],errors=[],links=new Map(),checks=[];let host=null,serial=0,chain=Promise.resolve();
async function emit(index,event){if(pages[index]&&!pages[index].isClosed())await pages[index].evaluate(e=>DemonStarNative.receive(e),event);}
async function drop(id){const link=links.get(id);if(!link)return;links.delete(id);await emit(link.host,{type:'disconnected',peer:id});await emit(link.client,{type:'disconnected',peer:'host'});}
async function native(index,raw){const r=JSON.parse(raw),reply=(value,error)=>r.requestId?emit(index,{requestId:r.requestId,value,error}):null;
  if(r.method==='capabilities')return reply({lan:true,haptics:false,platform:index%2?'ios':'android'});
  if(r.method==='host'){host=index;return reply({addresses:['192.168.42.1'],port:37654});}
  if(r.method==='join'){if(host===null)return reply(null,'connect-failed');const id='peer-'+(++serial);links.set(id,{host,client:index});await emit(host,{type:'connected',peer:id});await emit(index,{type:'connected',peer:'host'});return reply({peer:'host'});}
  if(r.method==='send'){for(const [id,l] of [...links]){if(l.host===index&&(r.peer==='*'||r.peer===id))await emit(l.client,{type:'message',peer:'host',data:r.data});else if(l.client===index&&r.peer==='host')await emit(l.host,{type:'message',peer:id,data:r.data});}return reply(true);}
  if(r.method==='stop'){for(const [id,l] of [...links])if(l.host===index||l.client===index)await drop(id);if(host===index)host=null;return reply(true);}
  if(r.method==='drop'){await drop(r.peer);return reply(true);}return reply(true);
}
try{
  for(let i=0;i<3;i++){
    const context=await browser.newContext({viewport:{width:480,height:900},locale:'en-US'}),page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push({device:i,error:e.message}));
    await page.exposeFunction('__nativeFixture',raw=>{chain=chain.then(()=>native(i,raw));return chain;});
    await page.addInitScript(()=>{window.DemonStarHost={command:raw=>{window.__nativeFixture(raw);}};const listen=window.addEventListener.bind(window);window.addEventListener=(type,...args)=>{if(type!=='blur'&&type!=='focus')listen(type,...args);};});
    await page.goto(process.env.GAME_URL||'http://127.0.0.1:4173');await page.waitForFunction(()=>window.StarfallApp&&StarfallApp.native.capabilities.lan);await page.locator('#settings').click();await page.locator('#lan-settings').click();
  }
  await pages[1].evaluate(()=>{StarfallApp.input.config.mousePlayer=2;});
  await pages[0].locator('#lan-host').click();await pages[0].waitForFunction(()=>StarfallApp.lan.status==='lobby');const code=await pages[0].evaluate(()=>StarfallApp.lan.code);
  for(let i=1;i<2;i++){await pages[i].locator('#lan-address').fill('192.168.42.1');await pages[i].locator('#lan-code').fill(code);await pages[i].locator('#lan-join').click();await pages[i].waitForFunction(()=>StarfallApp.lan.status==='lobby');assert.equal(await pages[i].evaluate(()=>StarfallApp.lan.localSlot),i+1);}
  await pages[2].locator('#lan-address').fill('192.168.42.1');await pages[2].locator('#lan-code').fill(code);await pages[2].locator('#lan-join').click();await pages[2].waitForFunction(()=>StarfallApp.lan.status==='rejected');assert.equal(await pages[2].evaluate(()=>StarfallApp.lan.error),'room-full');assert.equal(await pages[2].evaluate(()=>StarfallApp.game.phase),'menu');checks.push('third-player-rejected-without-entering-game');
  const active=pages.slice(0,2);await pages[0].waitForFunction(()=>StarfallApp.lan.members.length===2);await pages[0].getByRole('button',{name:'Launch together',exact:true}).click();await Promise.all(active.map(p=>p.waitForFunction(()=>StarfallApp.game.phase==='playing'&&StarfallApp.game.players.length===2)));checks.push('two-device-menu-room-launch');
  await pages[0].evaluate(()=>{const g=StarfallApp.game;g.recordEvents=[];g.enemies=[];g.bullets=[];for(const p of g.players)p.invincible=999;});
  assert.equal(await pages[1].locator('#joystick-2').isVisible(),false);assert.equal(await pages[1].locator('#fire').getAttribute('aria-label'),'Player 2 fire');assert.equal(await pages[1].locator('#coop-hud .coop-player').count(),2);
  const before=await pages[0].evaluate(()=>StarfallApp.game.players.map(p=>p.x));await pages[1].keyboard.down('d');await pages[1].keyboard.down('z');await pages[1].keyboard.press('Space');
  await pages[0].waitForFunction(()=>StarfallApp.game.players[1].shotsFired>=4&&StarfallApp.game.players[1].bombs===2);for(const [i,keys] of [[1,['d','z']]])for(const key of keys)await pages[i].keyboard.up(key);
  const moved=await pages[0].evaluate(()=>StarfallApp.game.players.map(p=>p.x));assert.ok(moved[1]>before[1]);checks.push('remote-owned-movement-fire-bomb');
  const mouseBefore=await pages[0].evaluate(()=>StarfallApp.game.players.map(p=>p.shotsFired)),field=await pages[1].evaluate(()=>StarfallApp.renderer.layout);assert.equal(await pages[1].evaluate(()=>StarfallApp.input.mouseOwner),1);await pages[1].mouse.move(field.x+100*field.scale,field.y+150*field.scale);await pages[1].mouse.down();await pages[0].waitForFunction(before=>StarfallApp.game.players[1].shotsFired>before[1],mouseBefore);await pages[1].mouse.up();await pages[0].waitForFunction(()=>StarfallApp.game.players[1].bombCooldown<=0);await pages[1].mouse.click(field.x+100*field.scale,field.y+150*field.scale,{button:'right'});await pages[0].waitForFunction(()=>StarfallApp.game.players[1].bombs===1);assert.equal(await pages[0].evaluate(()=>StarfallApp.game.players[0].shotsFired),mouseBefore[0]);assert.equal(await pages[0].evaluate(()=>StarfallApp.game.players[0].bombs),3);checks.push('LAN-P2-inherits-mouse-assignment-and-owns-fire-and-bomb');
  await pages[1].locator('#pause').click();await Promise.all(active.map(p=>p.waitForFunction(()=>StarfallApp.game.phase==='paused')));const frame=await pages[0].evaluate(()=>StarfallApp.game.frame);for(const p of active)assert.equal(await p.evaluate(()=>StarfallApp.game.frame),frame);assert.equal(await pages[1].locator('#stage-settings').isDisabled(),true);checks.push('guest-pause-freezes-same-authoritative-frame');
  await pages[1].locator('#control-settings').click();assert.deepEqual(await pages[1].locator('#mouse-player option').evaluateAll(nodes=>nodes.map(n=>n.value)),['0','1']);assert.equal(await pages[1].locator('#mouse-player').inputValue(),'1');assert.ok((await pages[1].locator('#mouse-player option:checked').textContent()).includes('Player 2'));assert.equal(await pages[1].evaluate(()=>StarfallApp.input.config.mousePlayer),2);await pages[1].getByRole('button',{name:'Back to settings',exact:true}).click();
  const languageState=await pages[1].evaluate(()=>JSON.stringify({players:StarfallApp.game.players,score:StarfallApp.game.score,stage:StarfallApp.game.stage.id,frame:StarfallApp.game.frame}));await pages[1].locator('#language').selectOption('zh-Hant');assert.equal(await pages[1].evaluate(()=>JSON.stringify({players:StarfallApp.game.players,score:StarfallApp.game.score,stage:StarfallApp.game.stage.id,frame:StarfallApp.game.frame})),languageState);assert.equal(await pages[0].locator('html').getAttribute('lang'),'en');checks.push('client-language-is-local-and-preserves-paused-combat');
  await pages[0].locator('#stage-settings').click();await pages[0].locator('[data-stage="2"]').click();await Promise.all(active.map(p=>p.waitForFunction(()=>StarfallApp.game.stage.id===2)));checks.push('host-stage-change-replicated');
  await pages[0].evaluate(()=>{StarfallApp.game.players[1].side=4;StarfallApp.lan.flush();});await pages[1].evaluate(()=>DemonStarNative.request('stop'));await pages[0].waitForFunction(()=>StarfallApp.game.phase==='paused'&&StarfallApp.game.players[1].connected===false);await pages[1].waitForFunction(()=>StarfallApp.lan.status==='disconnected');await pages[1].getByRole('button',{name:'重新連線',exact:true}).click();await pages[1].waitForFunction(()=>StarfallApp.lan.status==='playing'&&StarfallApp.game.players[1].side===4);assert.equal(await pages[1].evaluate(()=>StarfallApp.lan.localSlot),2);checks.push('reconnect-retains-second-seat-and-equipment');
  await pages[0].evaluate(()=>{const g=StarfallApp.game;g.score=12345;g.loadStage(3);StarfallApp.lan.flush();document.getElementById('pause').click();});await pages[0].locator('#save-settings').click();await pages[0].locator('[data-save="1"]').click();await pages[0].getByRole('button',{name:'Back to settings',exact:true}).click();await pages[0].locator('#stage-settings').click();await pages[0].locator('[data-stage="4"]').click();await pages[0].locator('#pause').click();await pages[0].locator('#save-settings').click();await pages[0].locator('[data-load="1"]').click();await Promise.all(active.map(p=>p.waitForFunction(()=>StarfallApp.game.stage.id===3&&StarfallApp.game.score===12345&&StarfallApp.game.players[1].side===4)));checks.push('host-checkpoint-load-restores-both-players-equipment-and-score');
  assert.equal(await pages[2].evaluate(()=>StarfallApp.game.phase),'menu');assert.equal(await pages[2].evaluate(()=>StarfallApp.lan.authenticated),false);await pages[0].screenshot({path:'artifacts/m210-lan-host.png'});await pages[1].screenshot({path:'artifacts/m210-lan-blue-client.png'});assert.deepEqual(errors,[]);
  const report={status:'passed',checks,scope:'Two admitted Chrome device fixtures plus one rejected third device with the real app/session/codec; native hotspot interoperability is a separate gate',errors};await writeFile('artifacts/m210-lan-browser.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{for(const p of pages)try{await p.evaluate(()=>StarfallApp.lan.leave());}catch{}await browser.close();}
